"""
build_json.py — rebuild pipeline/map_data.json from wc2026_players.csv + wc2026_coaches.csv.

Reads:   pipeline/wc2026_players.csv
         pipeline/wc2026_coaches.csv  (optional — adds coaches with role:"coach")
         pipeline/countries.json  (generated by pipeline/fetch_countries.py)
Writes:  pipeline/map_data.json

Preserves wikiTitle from the existing JSON when player names match, so this
script is safe to re-run after the CSV is updated without losing the
Wikipedia identity resolved by add_wiki_urls.py (which also writes the
per-language title files, pipeline/wiki_<lang>.json, that wikiTitle joins
into). map_data.json is a pipeline-internal intermediate — pipeline/load.py
is its only consumer; the frontend-facing successor is data/v2/map.json,
exported from pipeline/mundial.db by pipeline/export.py.

Population data (pop) is derived from countries.json (World Bank via fetch_countries.py).
Every nation / birth_country name is resolved to a canonical iso2 via
country_registry.py before being written out — an unrecognized name fails the
build loudly instead of silently writing id: null.
"""
import json, csv, sys
from pathlib import Path
from collections import defaultdict

import country_registry as reg

PIPELINE       = Path(__file__).parent
CSV_PATH       = PIPELINE / "wc2026_players.csv"
COACHES_PATH   = PIPELINE / "wc2026_coaches.csv"
JSON_PATH      = PIPELINE / "map_data.json"
COUNTRIES_PATH = PIPELINE / "countries.json"

# ── Load countries.json — authoritative source for numeric IDs + population ───
with open(COUNTRIES_PATH, encoding="utf-8") as f:
    countries_raw = json.load(f)

# lowercase alpha2 → population in millions
alpha2_to_pop_M = {v["alpha2"].lower(): v["population"] / 1_000_000
                   for v in countries_raw.values() if v.get("population")}

# Most recent year present in World Bank population data
pop_updated = max(
    (v["pop_year"] for v in countries_raw.values() if v.get("pop_year")),
    default="",
)

# ── Load existing JSON (for wikiTitle) ───────────────────────────────────────
with open(JSON_PATH, encoding="utf-8") as f:
    existing = json.load(f)

# Build (name, nation) → wikiTitle cache from existing players (exports +
# natives), so re-running this script doesn't lose the Wikipedia identity
# add_wiki_urls.py already resolved. Keying by name alone would collide two
# different people who share a name on different national teams (e.g. two
# "Emiliano Martínez"s, Argentina and Uruguay) — one would silently steal the
# other's wikiTitle on every rebuild.
wiki_cache = {}
for rec in existing.get("data", []):
    for p in rec.get("players", []):
        if p.get("wikiTitle"):
            wiki_cache[(p["name"], p["nation"])] = {"wikiTitle": p["wikiTitle"]}
for nation, players in existing.get("natives", {}).items():
    for p in players:
        key = (p["name"], nation)
        if p.get("wikiTitle") and key not in wiki_cache:
            wiki_cache[key] = {"wikiTitle": p["wikiTitle"]}

# ── Read CSV ──────────────────────────────────────────────────────────────────
players = []
with open(CSV_PATH, encoding="utf-8-sig") as f:
    for row in csv.DictReader(f):
        players.append({
            "name":          row["player"],
            "surname":       row["surname"],
            "shirtNumber":   int(row["number"]) if row["number"] else None,
            "nation":        row["nation"],
            "birth_city":    row["birth_city"],
            "birth_country": row["birth_country"],
            "caps":          int(row["caps"]) if row["caps"] else 0,
        })

# ── Read coaches CSV (optional) ──────────────────────────────────────────────
if COACHES_PATH.exists():
    with open(COACHES_PATH, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            if not row["birth_country"]:
                continue
            players.append({
                "name":          row["coach"],
                "surname":       row.get("surname", ""),
                "nation":        row["nation"],
                "birth_city":    row.get("birth_city", ""),
                "birth_country": row["birth_country"],
                "caps":          0,
                "role":          "coach",
            })

# ── Normalize country name variants ──────────────────────────────────────────
# Historical-entity judgment calls (Soviet Union, West Germany, ...) live in
# country_registry — they're dataset interpretation, not universal country
# identity, so resolve_iso2() doesn't apply them automatically.
for p in players:
    p["birth_country"] = reg.HISTORICAL_BIRTH_COUNTRY_ALIASES.get(
        p["birth_country"], p["birth_country"])
    if p["birth_country"] in reg.INVALID_BIRTH_COUNTRY_VALUES:
        p["birth_country"] = ""

# ── Fix known-wrong birth cities, then resolve "United Kingdom" → home nation ─
# Wikidata sometimes returns a country/region name instead of a city.
BIRTH_CITY_OVERRIDES = {
    "Aaron Hickey":  ("Glasgow",     "Scotland"),   # Wikidata returned "Scotland"
    "Callan Elliot": ("Kilmarnock",  "Scotland"),   # Wikidata returned "Scotland"
}
# UK city -> home nation table lives in country_registry.py (shared with
# wc2026_coaches.py, which faces the same "United Kingdom" ambiguity).
uk_unresolved = []
for p in players:
    city, country = p["birth_city"], p["birth_country"]
    if p["name"] in BIRTH_CITY_OVERRIDES:
        p["birth_city"], p["birth_country"] = BIRTH_CITY_OVERRIDES[p["name"]]
    elif country == "United Kingdom":
        resolved = reg.resolve_uk_home_nation(city)
        if resolved:
            p["birth_country"] = resolved
        else:
            uk_unresolved.append(f"{city!r} ({p['name']} / {p['nation']})")

if uk_unresolved:
    print("UK city -> home nation resolution failed:", file=sys.stderr)
    for entry in sorted(set(uk_unresolved)):
        print(f"  {entry}", file=sys.stderr)
    print("  Add these cities to UK_CITY_TO_NATION in pipeline/country_registry.py",
          file=sys.stderr)
    sys.exit(1)

# ── Resolve every nation / birth_country to a canonical iso2 + display name ──
# A name that doesn't resolve is a new upstream spelling variant — fail the
# build instead of silently writing id: null (see pipeline/country_registry.py).
# Rewriting to display_name(iso2) here (not just recording the iso2) matters:
# two raw spellings of the same country ("U.S." vs "United States") must
# collapse to one identical grouping key, or they silently form two records.
raw_to_iso2 = {}
resolution_errors = []
for p in players:
    for field in ("nation", "birth_country"):
        name = p[field]
        if not name or name in raw_to_iso2:
            continue
        try:
            raw_to_iso2[name] = reg.resolve_iso2(name)
        except reg.UnknownCountryError as e:
            resolution_errors.append(str(e))

if resolution_errors:
    print("Country resolution failed:", file=sys.stderr)
    for err in sorted(set(resolution_errors)):
        print(f"  {err}", file=sys.stderr)
    sys.exit(1)

country_iso2 = {}  # display name -> iso2, built while normalizing below
for p in players:
    for field in ("nation", "birth_country"):
        if p[field]:
            iso2 = raw_to_iso2[p[field]]
            p[field] = reg.display_name(iso2)
            country_iso2[p[field]] = iso2

# ── Build data["data"] — exports (birth_country ≠ nation) ────────────────────
by_birth = defaultdict(list)
for p in players:
    bc = p["birth_country"]
    if bc and bc != p["nation"]:
        by_birth[bc].append(p)

data_records = []
for country, group in sorted(by_birth.items(), key=lambda x: -len(x[1])):
    nations_map = defaultdict(int)
    for p in group:
        nations_map[p["nation"]] += 1

    enriched_players = []
    for p in group:
        obj = {"name": p["name"], "nation": p["nation"], "caps": p["caps"]}
        if p.get("role"):
            obj["role"] = p["role"]
        if p.get("surname"):
            obj["surname"] = p["surname"]
        if p.get("shirtNumber") is not None:
            obj["shirtNumber"] = p["shirtNumber"]
        key = (p["name"], p["nation"])
        if key in wiki_cache:
            obj.update(wiki_cache[key])
        enriched_players.append(obj)
    enriched_players.sort(key=lambda p: (0 if p.get("role") != "coach" else 1, -p["caps"]))

    top5 = enriched_players[:5]

    iso2 = country_iso2.get(country)

    data_records.append({
        "country": country,
        "id":      reg.canonical_id(iso2) if iso2 else None,
        "iso2":    iso2,
        "count":   len(group),
        "nations": sorted([[n, c] for n, c in nations_map.items()], key=lambda x: -x[1]),
        "top":     top5,
        "players": enriched_players,
    })

data_records.sort(key=lambda r: -r["count"])

# ── Build data["natives"] — born + plays for same country ────────────────────
natives = defaultdict(list)
for p in players:
    if p["birth_country"] == p["nation"]:
        obj = {"name": p["name"], "caps": p["caps"]}
        if p.get("role"):
            obj["role"] = p["role"]
        if p.get("surname"):
            obj["surname"] = p["surname"]
        if p.get("shirtNumber") is not None:
            obj["shirtNumber"] = p["shirtNumber"]
        key = (p["name"], p["nation"])
        if key in wiki_cache:
            obj.update(wiki_cache[key])
        natives[p["nation"]].append(obj)

for nation in natives:
    natives[nation].sort(key=lambda p: -p["caps"])

# ── Build pop + capital keyed by lowercase alpha2 ────────────────────────────
pop_data     = {a2: round(pop, 2) for a2, pop in alpha2_to_pop_M.items()}
capital_data = {v["alpha2"].lower(): v["capital"]
                for v in countries_raw.values() if v.get("capital")}

# ── Assemble and write ────────────────────────────────────────────────────────
output = {
    "data":       data_records,
    "pop":        pop_data,
    "capital":    capital_data,
    "natives":    dict(natives),
    "popSource":  "data.worldbank.org/indicator/SP.POP.TOTL",
    "popUpdated": pop_updated,
}

with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, separators=(",", ":"))

exports = sum(r["count"] for r in data_records)
native_total = sum(len(v) for v in natives.values())
coach_exports = sum(1 for r in data_records for p in r["players"] if p.get("role") == "coach")
coach_natives = sum(1 for ps in natives.values() for p in ps if p.get("role") == "coach")
print(f"Wrote {JSON_PATH}")
print(f"  {len(data_records)} birth countries, {exports} exports (incl. {coach_exports} coaches)")
print(f"  {len(natives)} nations, {native_total} natives (incl. {coach_natives} coaches)")
print(f"  {exports + native_total} total")
