"""
build_json.py — rebuild wc2026_map_data.json from wc2026_players.csv + wc2026_coaches.csv.

Reads:   pipeline/wc2026_players.csv
         pipeline/wc2026_coaches.csv  (optional — adds coaches with role:"coach")
         countries.json  (project root — generated by pipeline/fetch_countries.py)
Writes:  wc2026_map_data.json  (project root)

Preserves wiki_langs / wiki from the existing JSON when player names match,
so this script is safe to re-run after the CSV is updated without losing the
Wikipedia enrichment produced by add_wiki_urls.py.

Population data (pop) is derived from countries.json (World Bank via fetch_countries.py).
Country → topojson numeric ID mapping is seeded from the existing JSON too;
new birth countries not yet in the JSON get id=null (rendered but not interactive
on the map — a subsequent data release can add the correct numeric ID).
"""
import json, csv
from pathlib import Path
from collections import defaultdict

DATA_DIR       = Path(__file__).parent.parent / "data"
CSV_PATH       = Path(__file__).parent / "wc2026_players.csv"
COACHES_PATH   = Path(__file__).parent / "wc2026_coaches.csv"
JSON_PATH      = DATA_DIR / "map_data.json"
COUNTRIES_PATH = Path(__file__).parent / "countries.json"

# ── Load countries.json — authoritative source for numeric IDs + population ───
with open(COUNTRIES_PATH, encoding="utf-8") as f:
    countries_raw = json.load(f)

# Aliases: CSV birth-country names that differ from mledoze common names
CSV_TO_MLEDOZE = {
    "Czech Republic":             "Czechia",
    "Turkey":                     "Türkiye",
    "U.S.":                       "United States",
    "Kingdom of the Netherlands": "Netherlands",
}

# mledoze name → lowercase alpha2  /  mledoze name → numeric id
name_to_alpha2 = {v["name"]: v["alpha2"].lower() for v in countries_raw.values()}
name_to_id     = {v["name"]: int(k)              for k, v in countries_raw.items()}

# lowercase alpha2 → population in millions
alpha2_to_pop_M = {v["alpha2"].lower(): v["population"] / 1_000_000
                   for v in countries_raw.values() if v.get("population")}

# Most recent year present in World Bank population data
pop_updated = max(
    (v["pop_year"] for v in countries_raw.values() if v.get("pop_year")),
    default="",
)

# ── Load existing JSON (for id overrides, wiki_langs) ────────────────────────
with open(JSON_PATH, encoding="utf-8") as f:
    existing = json.load(f)

# Seed country → numeric id from existing JSON, then fill gaps from countries.json
country_id = {r["country"]: r.get("id") for r in existing.get("data", [])}
for name in list(country_id):
    if country_id[name] is None:
        lookup = CSV_TO_MLEDOZE.get(name, name)
        country_id[name] = name_to_id.get(lookup)  # stays None if unknown

# Build name → wiki_langs cache from existing players (exports + natives)
wiki_cache = {}
for rec in existing.get("data", []):
    for p in rec.get("players", []):
        if p.get("wiki_langs"):
            wiki_cache[p["name"]] = {"wiki_langs": p["wiki_langs"], "wiki": p.get("wiki")}
for players in existing.get("natives", {}).values():
    for p in players:
        if p.get("wiki_langs") and p["name"] not in wiki_cache:
            wiki_cache[p["name"]] = {"wiki_langs": p["wiki_langs"], "wiki": p.get("wiki")}

# ── Read CSV ──────────────────────────────────────────────────────────────────
players = []
with open(CSV_PATH, encoding="utf-8-sig") as f:
    for row in csv.DictReader(f):
        players.append({
            "name":          row["player"],
            "nation":        row["nation"],
            "birth_city":    row["birth_city"],
            "birth_country": row["birth_country"],
            "caps":          int(row["caps"]) if row["caps"] else 0,
        })

# ── Read coaches CSV (optional) ──────────────────────────────────────────────
if COACHES_PATH.exists():
    with open(COACHES_PATH, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            if not row["birth_country"]:
                continue
            players.append({
                "name":          row["coach"],
                "nation":        row["nation"],
                "birth_city":    row.get("birth_city", ""),
                "birth_country": row["birth_country"],
                "caps":          0,
                "role":          "coach",
            })

# ── Normalize country name variants ──────────────────────────────────────────
BIRTH_COUNTRY_ALIASES = {
    "Democratic Republic of the Congo": "DR Congo",
    "Zaire (now DR Congo)":             "DR Congo",
    "U.S.":                             "United States",
    "West Germany":                     "Germany",
    "Soviet Union":                     "Uzbekistan",   # all current cases are Uzbek-born players
    "Netherlands Antilles":             "Curaçao",
}
# Wikidata occasionally returns "]" as a malformed country — discard it.
INVALID_COUNTRIES = {"]"}
for p in players:
    p["birth_country"] = BIRTH_COUNTRY_ALIASES.get(p["birth_country"], p["birth_country"])
    if p["birth_country"] in INVALID_COUNTRIES:
        p["birth_country"] = ""

# ── Fix known-wrong birth cities, then resolve "United Kingdom" → home nation ─
# Wikidata sometimes returns a country/region name instead of a city.
BIRTH_CITY_OVERRIDES = {
    "Aaron Hickey":  ("Glasgow",     "Scotland"),   # Wikidata returned "Scotland"
    "Callan Elliot": ("Kilmarnock",  "Scotland"),   # Wikidata returned "Scotland"
}
# Maps cities (incl. Greater London boroughs and towns) to UK home nations.
UK_CITY_TO_NATION = {
    # Scotland
    "Glasgow": "Scotland", "Edinburgh": "Scotland", "Aberdeen": "Scotland",
    "Inverness": "Scotland", "Dumfries": "Scotland", "Irvine": "Scotland",
    "Rutherglen": "Scotland", "Leuchars": "Scotland", "Dalry": "Scotland",
    "Balfron": "Scotland", "Kirriemuir": "Scotland", "Saltcoats": "Scotland",
    "Kilmarnock": "Scotland",
    # Wales
    "Cardiff": "Wales", "Swansea": "Wales",
    # Northern Ireland
    "Belfast": "Northern Ireland",
    # England — Greater London
    "London": "England", "Croydon": "England", "Ealing": "England",
    "Walthamstow": "England", "Barnet": "England", "Greenwich": "England",
    "Mitcham": "England", "Harold Wood": "England",
    "London Borough of Newham": "England",
    # England — North West
    "Manchester": "England", "Liverpool": "England", "Stockport": "England",
    "Warrington": "England", "Macclesfield": "England", "Lancaster": "England",
    # England — North East
    "Sunderland": "England", "Blyth": "England", "Whitley Bay": "England",
    "Washington": "England",
    # England — Yorkshire
    "Leeds": "England", "Sheffield": "England", "Barnsley": "England",
    # England — Midlands
    "Birmingham": "England", "Solihull": "England", "Northampton": "England",
    "Leicester": "England", "Stourbridge": "England",
    # England — East / South / South West
    "Milton Keynes": "England", "Cockermouth": "England", "Torquay": "England",
}
for p in players:
    city, country = p["birth_city"], p["birth_country"]
    if p["name"] in BIRTH_CITY_OVERRIDES:
        p["birth_city"], p["birth_country"] = BIRTH_CITY_OVERRIDES[p["name"]]
    elif country == "United Kingdom":
        resolved = UK_CITY_TO_NATION.get(city)
        if resolved:
            p["birth_country"] = resolved
        else:
            print(f"  ⚠ UK city not mapped: {city!r} ({p['name']} / {p['nation']})")

# ── Build data["data"] — exports (birth_country ≠ nation) ────────────────────
by_birth = defaultdict(list)
for p in players:
    bc = p["birth_country"]
    if bc and bc != p["nation"]:
        by_birth[bc].append(p)

data_records = []
for country, group in sorted(by_birth.items(), key=lambda x: -len(x[1])):
    nations_map = defaultdict(int)
    for p in group:
        nations_map[p["nation"]] += 1

    enriched_players = []
    for p in group:
        obj = {"name": p["name"], "nation": p["nation"], "caps": p["caps"]}
        if p.get("role"):
            obj["role"] = p["role"]
        if p["name"] in wiki_cache:
            obj.update(wiki_cache[p["name"]])
        enriched_players.append(obj)
    enriched_players.sort(key=lambda p: (0 if p.get("role") != "coach" else 1, -p["caps"]))

    top5 = enriched_players[:5]

    data_records.append({
        "country": country,
        "id":      country_id.get(country),
        "count":   len(group),
        "nations": sorted([[n, c] for n, c in nations_map.items()], key=lambda x: -x[1]),
        "top":     top5,
        "players": enriched_players,
    })

data_records.sort(key=lambda r: -r["count"])

# ── Build data["natives"] — born + plays for same country ────────────────────
natives = defaultdict(list)
for p in players:
    if p["birth_country"] == p["nation"]:
        obj = {"name": p["name"], "caps": p["caps"]}
        if p.get("role"):
            obj["role"] = p["role"]
        if p["name"] in wiki_cache:
            obj.update(wiki_cache[p["name"]])
        natives[p["nation"]].append(obj)

for nation in natives:
    natives[nation].sort(key=lambda p: -p["caps"])

# ── Build pop + capital keyed by lowercase alpha2 ────────────────────────────
pop_data     = {a2: round(pop, 2) for a2, pop in alpha2_to_pop_M.items()}
capital_data = {v["alpha2"].lower(): v["capital"]
                for v in countries_raw.values() if v.get("capital")}

# ── Assemble and write ────────────────────────────────────────────────────────
output = {
    "data":       data_records,
    "pop":        pop_data,
    "capital":    capital_data,
    "natives":    dict(natives),
    "popSource":  "data.worldbank.org/indicator/SP.POP.TOTL",
    "popUpdated": pop_updated,
}

with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, separators=(",", ":"))

exports = sum(r["count"] for r in data_records)
native_total = sum(len(v) for v in natives.values())
coach_exports = sum(1 for r in data_records for p in r["players"] if p.get("role") == "coach")
coach_natives = sum(1 for ps in natives.values() for p in ps if p.get("role") == "coach")
print(f"Wrote {JSON_PATH}")
print(f"  {len(data_records)} birth countries, {exports} exports (incl. {coach_exports} coaches)")
print(f"  {len(natives)} nations, {native_total} natives (incl. {coach_natives} coaches)")
print(f"  {exports + native_total} total")
